# Generated by Django 2.2.1 on 2019-08-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('zip_code', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'application',
            },
        ),
    ]
