# Generated by Django 2.2.1 on 2019-08-01 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20190801_1700'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='Details',
        ),
    ]
